export default {
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  REGISTER: 'Register',
  ERROR: 'Error',
  SUCCESS: 'Success',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  NAME: 'Name',
  PROFILE_SUCCESS_ALERT_MESSAGE: 'Profile successfully updated!',
  HELPER_TEXT_PREFIX: 'Current: ',
  PERCENTAGE: '%',
  INS: '₪',
  TAX_COMMISSION: 'Tax & Commission',
  INSURANCES: 'Insurances',
  TAX_REFUNDS: 'Tax Refunds',
  TAX_POINTS: 'Tax Points',
  COMMISSION_RATE: 'Commission Rate',
  COMPULSORY: 'Compulsory',
  COLLATERAL: 'Collateral',
  USERS_DATA: 'USERS_DATA',
  PROFILE: 'PROFILE',
  EXPENSES: 'EXPENSES',
  USER_PROFILE: 'USER_PROFILE',
  DEFAULT_USER_PROFILE: {
    taxRefunds: false,
    taxPoints: 2.25,
    commissionRate: 5,
    compulsory: 3700,
    collateral: 500,
    timestamp: Date.now(),
  },
  email: 'email',
  password: 'password',
  name: 'name',
  taxRefunds: 'taxRefunds',
  taxPoints: 'taxPoints',
  commissionRate: 'commissionRate',
  compulsory: 'compulsory',
  collateral: 'collateral',
  expensesTypes: [
    {
      value: 'fuel',
      label: 'Fuel',
      icon: 'fuel',
    },
    {
      value: 'maintenance',
      label: 'Maintenance',
      icon: 'screwdriver',
    },
    {
      value: 'equipment',
      label: 'Equipment',
      icon: 'racing-helmet',
    },
  ],
  REQUIRED: 'Required',
  SUBMIT_EXPENSE_SUCCESS_ALERT_MESSAGE: 'Expense successfully Added!',
  SUBMIT_SHIFT_SUCCESS_ALERT_MESSAGE: 'Shift successfully Added!',
  EXPENSE: 'Expense',
  TYPE: 'Type',
  type: 'type',
  COST: 'Cost',
  cost: 'cost',
  COMMENT: 'Comment',
  comment: 'comment',
  SHIFT: 'Shift',
  DELIVERIES: 'Deliveries',
  deliveries: 'deliveries',
  WOLT: 'Wolt',
  wolt: 'wolt',
  CREDIT_TIPS: 'Credit Tips',
  credit_tips: 'creditTips',
  CASH_TIPS: 'Cash Tips',
  cash_tips: 'cashTips',
  CREDIT: 'Credit',
  CASH: 'Cash',
  SHIFTS: 'SHIFTS',
  VAT: 0.17,
};
