export default {
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  REGISTER: 'Register',
  ERROR: 'Error',
  SUCCESS: 'Success',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  NAME: 'Name',
  PROFILE_SUCCESS_ALERT_MESSAGE: 'Profile successfully updated!',
  HELPER_TEXT_PREFIX: 'Current: ',
  PERCENTAGE: '%',
  INS: '₪',
  TAX_COMMISSION: 'Tax & Commission',
  INSURANCES: 'Insurances',
  TAX_REFUNDS: 'Tax Refunds',
  TAX_POINTS: 'Tax Points',
  COMMISSION_RATE: 'Commission Rate',
  COMPULSORY: 'Compulsory',
  COLLATERAL: 'Collateral',
};
